### ISSUE TITLE
[TODO LIST] Plan et article.

### ISSUE THREAD

**Issue by junthong** [junthong/junthong.github.io#4]
Ci-dessous un plan du contenu à produire.

Basic
- [ ] Grade
- [ ] Materiel essentiel
- [ ] Technique de coupe
- [ ] Panel lining
- [ ] Reparer une pièce cassé
- [ ] Top gunpla pour commencer
- [ ] Top gunpla ever

Reshaping 
- [ ]  Panel scribing
- [ ] Effacer l'espace entre les pièces (cement)
- [ ]  Styrene
- [ ]  Putty

Peinture
- [ ] Nettoyage d'un aerographe
- [ ] Manipulation d'un Aerographe
- [ ] Thinner
- [ ] Candy paint
- [ ] Marble effect
- [ ] Gundam marker

Materiel
- [] Reshaping
- [ ]  Ref peinture Mr hobby
- [ ]  Ref peinture vallejo
- [ ]  Ref gundam marker
